const ASCII_CODE_OF_LOWERCASE_A = 97;
const ASCII_CODE_OF_LOWERCASE_Z = 122;
const NEGATIVE_NUMBER_EXCEPTION_MSG = "Negatives not allowed:";
const REGEX_TO_MATCH_NEGATIVE_NUMBERS = /-\d+/g;

module.exports = {
  ASCII_CODE_OF_LOWERCASE_A,
  ASCII_CODE_OF_LOWERCASE_Z,
  NEGATIVE_NUMBER_EXCEPTION_MSG,
  REGEX_TO_MATCH_NEGATIVE_NUMBERS,
};
