const ASCII_CODE_OF_LOWERCASE_A = 97;
const ASCII_CODE_OF_LOWERCASE_Z = 122;
const NEGATIVE_NUMBER_EXCEPTION_MSG = "Negatives not allowed:";
const REGEX_TO_MATCH_NEGATIVE_NUMBERS = /-\d+/g;

const INPUT_STRING_IDENTIFICATION_SYMBOLS = {
  SEPERATOR_SYMBOL: "//",
  EVEN_IDENTIFICATION_SYMBOL: "1//",
  ODD_IDENTIFICATION_SYMBOL: "0//"
}

const DELIMITER_FILTER_TYPES = {
  FILTER_EVEN_NUMBERS: "odd_type",
  FILTER_ODD_NUMBERS: "even_type",
  NO_FILTER: "normal_type",
  NOT_HAS_DELIMITER_TEXT: "",
};

module.exports = {
  ASCII_CODE_OF_LOWERCASE_A,
  ASCII_CODE_OF_LOWERCASE_Z,
  NEGATIVE_NUMBER_EXCEPTION_MSG,
  REGEX_TO_MATCH_NEGATIVE_NUMBERS,
  DELIMITER_FILTER_TYPES,
  INPUT_STRING_IDENTIFICATION_SYMBOLS,
};
